<a href="https://colab.research.google.com/github/BOBcheeto/MIS433/blob/main/Copy_of_data_summarization_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: Data Summarization

In [142]:
import pandas as pd
import numpy as np

In [143]:
!pip install nycflights13

Requirement already satisfied: nycflights13 in /usr/local/lib/python3.12/dist-packages (0.0.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)

In [144]:
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## DataFrame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [145]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

## Exercises

Write Python scripts to answer the following questions.

In [146]:
# How many distinct airplanes are there in this dataset?
flights.tailnum.nunique()

4043

In [147]:
# Which hours of the day are the busiest?
# List the top 5 hours with the most flights.
flights.groupby('hour').size().sort_values(ascending=False).head(5)

hour
8     27242
6     25951
17    24426
15    23888
16    23002
dtype: int64

In [148]:
# Find all flights (identified by 'carrier' and 'flight')
# that always depart at least 60 minutes late.
late_flights = flights.groupby(['carrier', 'flight'])['dep_delay'].min()
late_flights = late_flights[late_flights >= 60]
late_flights

carrier  flight
9E       3283      104.0
         3297      120.0
         3546       64.0
         3583       95.0
         3588      115.0
         3682       66.0
         3760      217.0
B6       205        82.0
DL       390       334.0
         462       125.0
         809       298.0
         917       157.0
         2390       92.0
EV       4151       67.0
         4320       95.0
         4564       91.0
         4617      128.0
         5015       63.0
         5062      111.0
         5071       92.0
         5083       98.0
         5117      219.0
         5294      192.0
         5358       78.0
         5409       87.0
         5425       62.0
         5478      242.0
         5629       71.0
         5668      106.0
         5839       65.0
         5855      209.0
         6082      153.0
         6093      128.0
F9       2001       65.0
OO       8500       67.0
UA       18         95.0
         125        89.0
         348        93.0
         546        60.0
         640       115.0
         945        62.0
         993        69.0
         1510      278.0
US       1226      147.0
WN       217       195.0
         521       346.0
         718        78.0
         1019      203.0
         2521       79.0
         2529       75.0
         3032       90.0
         3791      151.0
YV       3799      168.0
Name: dep_delay, dtype: float64

In [149]:
# How many flights always depart at least 60 minutes late?
print(f'{len(late_flights)} flights always depart at least 60 minutes late')

53 flights always depart at least 60 minutes late

In [150]:
# Find all United Airlines (UA) flights (identified by 'carrier' and 'flight')
# that depart (at least) 60 minutes late.
UA_late_flights = flights[
    (flights.carrier == 'UA') &
    (flights.dep_delay >= 60)
    ]
UA_late_flights = UA_late_flights.groupby(['carrier', 'flight']).nunique()

UA_late_flights

                year  month  day  dep_time  sched_dep_time  dep_delay  \
carrier flight
UA      12         1      2    2         2               2          2
        15         1      7   18        22               6         22
        18         1      1    1         1               1          1
        32         1      1    1         1               1          1
        68         1      1    1         1               1          1
...              ...    ...  ...       ...             ...        ...
        1738       1      2    4         4               3          4
        1739       1      2    3         3               3          3
        1740       1      2    6         6               5          5
        1742       1      1    1         1               1          1
        1744       1      4    6         7               5          7

                arr_time  sched_arr_time  arr_delay  tailnum  origin  dest  \
carrier flight
UA      12             2               2          2        2       2     2
        15            24              10         22       12       1     1
        18             1               1          1        1       1     1
        32             1               1          1        1       1     1
        68             1               1          1        1       1     1
...                  ...             ...        ...      ...     ...   ...
        1738           4               3          4        4       1     2
        1739           3               3          3        3       1     2
        1740           6               5          6        6       1     1
        1742           1               1          1        1       1     1
        1744           7               5          7        6       2     2

                air_time  distance  hour  minute  time_hour
carrier flight
UA      12             2         2     2       2          2
        15            18         1     2       5         24
        18             1         1     1       1          1
        32             1         1     1       1          1
        68             1         1     1       1          1
...                  ...       ...   ...     ...        ...
        1738           4         2     3       3          4
        1739           3         2     2       3          3
        1740           6         1     4       5          6
        1742           1         1     1       1          1
        1744           7         2     2       5          7

[854 rows x 17 columns]

In [151]:
# How many United Airlines (UA) flights depart (at least) 60 minutes late?
print(f'{len(UA_late_flights)} United Airlines (UA) flights depart (at least) 60 minutes late')

854 United Airlines (UA) flights depart (at least) 60 minutes late

In [152]:
# Which flights that always arrived on time in December?
december_flights = flights[flights.month == 12]
nlate_december_flights = december_flights.groupby(['carrier', 'flight'])['arr_delay'].max()
nlate_december_flights = nlate_december_flights[nlate_december_flights <= 0]

nlate_december_flights

carrier  flight
9E       2909      -7.0
         2919     -32.0
         2934     -22.0
         2939     -21.0
         2950       0.0
                   ...
WN       4313     -18.0
         4337     -22.0
         4490      -2.0
         4514      -2.0
         4976     -17.0
Name: arr_delay, Length: 330, dtype: float64

In [153]:
# How many flights always arrived on time in December?
print(f'{len(nlate_december_flights)} flights always arrived on time in December')

330 flights always arrived on time in December

In [154]:
# Create a dataframe 'cancelled' for all cancelled flights.
# Assumption: flights that are not cancelled should have values for dep_time.
cancelled_flights = flights[flights.dep_time.isnull()]

cancelled_flights

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
838,2013,1,1,NaN,1630,NaN,NaN,1815,NaN,EV,4308,N18120,EWR,RDU,NaN,416,16,30,2013-01-01T21:00:00Z
839,2013,1,1,NaN,1935,NaN,NaN,2240,NaN,AA,791,N3EHAA,LGA,DFW,NaN,1389,19,35,2013-01-02T00:00:00Z
840,2013,1,1,NaN,1500,NaN,NaN,1825,NaN,AA,1925,N3EVAA,LGA,MIA,NaN,1096,15,0,2013-01-01T20:00:00Z
841,2013,1,1,NaN,600,NaN,NaN,901,NaN,B6,125,N618JB,JFK,FLL,NaN,1069,6,0,2013-01-01T11:00:00Z
1777,2013,1,2,NaN,1540,NaN,NaN,1747,NaN,EV,4352,N10575,EWR,CVG,NaN,569,15,40,2013-01-02T20:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [155]:
# Look at the number of cancelled flights per day.
# Find the top 10 days with the most cancelled flights.
top_days_cancelled_flights = cancelled_flights.groupby(['year', 'month', 'day']).size().sort_values(ascending=False)
top_days_cancelled_flights.head(10)

year  month  day
2013  2      8      472
             9      393
      5      23     221
      12     10     204
      9      12     192
      3      6      180
             8      180
      12     5      158
             14     125
      6      28     123
dtype: int64

In [156]:
# Which carrier has the worst average arrival delay?
worst_carrier_arr_delay = flights.groupby('carrier')['arr_delay'].mean().sort_values(ascending=False)

print(f'{worst_carrier_arr_delay.index[0]} has the worst average arrival delay')

F9 has the worst average arrival delay

In [157]:
# Which plane (tailnum) has the worst on-time record?
worst_on_time_planes = flights.groupby('tailnum')['arr_delay'].mean().sort_values(ascending=False)

print(f'{worst_on_time_planes.index[0]} has the worst on-time record')

N844MH has the worst on-time record

In [158]:
# What time (hour) of day should you fly if you want to avoid delays as much as possible?
min_delays_flights = flights.groupby('hour')[['arr_delay', 'dep_delay']].mean()
min_delays_flights['total_avg_delay'] = min_delays_flights.arr_delay + min_delays_flights.dep_delay
min_delays_flights = min_delays_flights['total_avg_delay'].sort_values(ascending=True)

print(f'fly at {min_delays_flights.index[0]} to avoid delays as much as possible')

fly at 5 to avoid delays as much as possible

In [159]:
# For each destination, compute the total minutes of arrival delay.
total_arr_delay = flights.groupby('dest')['arr_delay'].sum()

total_arr_delay

dest
ABQ      1113.0
ACK      1281.0
ALB      6018.0
ANC       -20.0
ATL    190260.0
         ...
TPA     54749.0
TUL      9896.0
TVC      1232.0
TYS     13912.0
XNA      7406.0
Name: arr_delay, Length: 105, dtype: float64

In [160]:
# Find the worst days in terms of average arrival delay greater than 1 hour.
worst_days = flights.groupby(['year', 'month', 'day'])['arr_delay'].mean()
worst_days = worst_days[worst_days > 60].sort_values(ascending=False)

worst_days

year  month  day
2013  3      8      85.862155
      6      13     63.753689
      7      22     62.763403
      5      23     61.970899
Name: arr_delay, dtype: float64

In [161]:
# Find the number of carriers between each pair of origin and destination.
carrier_count = flights.groupby(['origin', 'dest'])['carrier'].nunique()

carrier_count

origin  dest
EWR     ALB     1
        ANC     1
        ATL     4
        AUS     2
        AVL     1
               ..
LGA     SYR     2
        TPA     2
        TVC     2
        TYS     1
        XNA     2
Name: carrier, Length: 224, dtype: int64